### ISSUE TITLE
Please indicate how third parties can Seek support

### ISSUE THREAD

**Issue by joethorley** [nhejazi/txshift#57]
https://github.com/openjournals/joss-reviews/issues/2447

**Comment by joethorley** [comment]
The review asks in the Documentation section whether 

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by nhejazi** [comment]
Thanks @joethorley for bringing up these issues. We had added https://github.com/nhejazi/txshift#issues and https://github.com/nhejazi/txshift#contributions (as well as https://github.com/nhejazi/txshift/blob/master/CONTRIBUTING.md) in order to address issues and contribution expectations for our users. Would you recommend documentation beyond these items? Happy to consider any such changes.

**Comment by joethorley** [comment]
Done
